jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "12.9"
      cache:
        directories:
          - "~/node_modules"
      script:
        - npm run test

    - stage: deploy
      env:
        - NAMESPACE="game-on-frontend"
        - SERVICE="game-on-app"
        - RELEASE_SCRIPT="https://gist.githubusercontent.com/ankjevel/fc444cdb248287a97242ced271ece388/raw"
      language: node_js
      node_js: "12.9"
      cache:
        directories:
          - "~/node_modules"
      script:
        - npm run test
      after_success:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - export REPO="${TRAVIS_REPO_SLUG,,}"
        - export TAG=$([ -z "$TRAVIS_TAG" ] && echo "latest" || echo "${TRAVIS_TAG/v/}")
        - docker build -t $REPO:$TAG .
        - docker push $REPO:$TAG
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            return 0
          fi
        - docker tag $REPO:$TAG $REPO:latest-tag-release
        - docker push $REPO:TAG
        - docker push $REPO:latest-tag-release
        - source <(curl "$RELEASE_SCRIPT" -s 2>&1)

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

notifications:
  email: false
